### ISSUE TITLE
iConvertMetersTime Exception thrown when self.TravelTime can't be retrieved

### ISSUE THREAD

**Issue by ZachBenz** [Ghawken/IndigoPlugin-iFindFriendMini#18]
I believe this is occurring due to a device that is frequently offline (i.e. powered down), but which I want to track when it is indeed occasionally powered up.  The below appears in my logs every polling cycle.

```
   FindFriendsMini Error           Exception:
Traceback (most recent call last):
  File "plugin.py", line 1076, in refreshDataForDev
    if 'labels' in follow['location'] and follow['location']['labels'] is not None:
TypeError: argument of type 'NoneType' is not iterable
   FindFriendsMini                 Possibility missing some data from icloud:  Is your account setup with FindFriends enabled on iOS/Mobile device?
   FindFriendsMini Error           iCovertMetersTime Exception:  Is Plugin Config probably setup? Is Travel Time a number?
Traceback (most recent call last):
  File "plugin.py", line 1701, in iConvertMetersTime
    secondsoftime = int(meters/float(self.travelTime))
ValueError: could not convert string to float: 
   FindFriendsMini Error           iCovertMetersTime Exception:  Is Plugin Config probably setup? Is Travel Time a number?
Traceback (most recent call last):
  File "plugin.py", line 1701, in iConvertMetersTime
    secondsoftime = int(meters/float(self.travelTime))
ValueError: could not convert string to float: 
   FindFriendsMini Error           iCovertMetersTime Exception:  Is Plugin Config probably setup? Is Travel Time a number?
Traceback (most recent call last):
  File "plugin.py", line 1701, in iConvertMetersTime
    secondsoftime = int(meters/float(self.travelTime))
ValueError: could not convert string to float: 
   FindFriendsMini Error           iCovertMetersTime Exception:  Is Plugin Config probably setup? Is Travel Time a number?
Traceback (most recent call last):
  File "plugin.py", line 1701, in iConvertMetersTime
    secondsoftime = int(meters/float(self.travelTime))
ValueError: could not convert string to float: 
   FindFriendsMini Error           iCovertMetersTime Exception:  Is Plugin Config probably setup? Is Travel Time a number?
Traceback (most recent call last):
  File "plugin.py", line 1701, in iConvertMetersTime
    secondsoftime = int(meters/float(self.travelTime))
ValueError: could not convert string to float: 
   FindFriendsMini Error           iCovertMetersTime Exception:  Is Plugin Config probably setup? Is Travel Time a number?
Traceback (most recent call last):
  File "plugin.py", line 1701, in iConvertMetersTime
    secondsoftime = int(meters/float(self.travelTime))
ValueError: could not convert string to float: 
```

**Comment by Ghawken** [comment]
Sorry - missed this completely
Coincidentally think latest update fixes (0.9.3)

**Comment by ZachBenz** [comment]
Just installed 0.9.3, and will watch my logs.  Thanks!

**Comment by ZachBenz** [comment]
Looks good; closing issue.
